### ISSUE TITLE
Postgres issue when running `docker compose -f docker-compose.yml up`

### ISSUE THREAD

**Issue by sahuguet** [OasisLMF/OasisModels#24]
When running `docker compose -f docker-compose.yml up`,
I am getting

```
server-db-1                    | postgres: could not find the database system
server-db-1                    | Expected to find it in the directory "/var/lib/postgresql/data",
```

I tried on `PiWindSinglePeril` and `ParisWindstorm`.

System info
```
OS = Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103 arm64
Docker version 28.0.4, build b8034c0
```

**Comment by KamalCharles** [comment]
On macOS (M1/M2), we need to  use the linux/amd64 platform for Postgres to ensure compatibility.


**MAC OS**

docker-compose.yml, update the server-db service


```
server-db:
  image: postgres:14
  platform: linux/amd64   #  compatibility on macOS (M1/M2)
  ports:
    - 33307:3306          
```
Fixes ARM/Postgres incompatibility
